---
title: "BIHS_explore"
author: "Lila Cardell"
date: "October 24, 2019"
output: pdf_document
#fontsize: 11pt

#bibliography: nutrition.bibtex
---

Set working directory and install packages
```{r setup, include=FALSE}


knitr::opts_chunk$set(echo = FALSE,root.dir='C:/Users/lilac2/Box/BIHS Project',warning = FALSE, message=FALSE)
options(scipen=999)
set.seed(12345)
###  Check for and load Packages   ###

## Clear worksace
rm(list = ls())
gc()

## This function will check if a package is installed, and if not, install it
pkgTest  =  function(x) {
  if (!require(x, character.only = TRUE))
  {
    install.packages(x, dep = TRUE)
    if(!require(x, character.only = TRUE)) stop("Package not found")
  }
}

## These lines load the required packages
packages  =  c('data.table','tidyverse','haven','stargazer','plm','lubridate','survey','psych','knitr','xtable','tables','kableExtra',
              'MASS','matrixcalc','car','stringr','styler','readxl','magrittr','sjmisc') ## you can add more packages here
lapply(packages, pkgTest)

```



1. Import BIHS and nutrition data
```{r import data,results='hide'}
# Read in data for project
#readincsv  =  function(x,y,z){
 # x_y_2011 = read_csv("Data/Raw Data/bihs_2011_2012/household/data/csv/z_mod_x_y.CSV")
#}
#files  =  c('data.table','tidyverse','haven','stargazer','plm','lubridate',
 #             'MASS','matrixcalc','car','stringr')
#lapply(files, readincsv)
setwd("C:/Users/lilac2/Box/BIHS Project")
census_2011 = read_dta("Data/Raw Data/bihs_2011_2012/census/data/001_census_ftf.dta")

# path = "~Data/Raw Data/bihs_2011_2012/household/data/"
# out.file<-""
# 
# file.names <- dir(path, pattern ="_male")
# 
# for(i in 1:length(file.names)){
#   file <- read.table(file.names[i],header=TRUE, sep=";", stringsAsFactors=FALSE)
#   out.file <- rbind(out.file, file)
# 
# 

a_m_2011 = read_dta("Data/Raw Data/bihs_2011_2012/household/data/001_mod_a_male.dta")
a_f_2011 = read_dta("Data/Raw Data/bihs_2011_2012/household/data/002_mod_a_female.dta")
b1_m_2011 = read_dta("Data/Raw Data/bihs_2011_2012/household/data/003_mod_b1_male.dta")
b2_m_2011 = read_dta("Data/Raw Data/bihs_2011_2012/household/data/004_mod_b2_male.dta")
c_m_2011 = read_dta("Data/Raw Data/bihs_2011_2012/household/data/005_mod_c_male.dta")
o1_f_2011 = read_dta("Data/Raw Data/bihs_2011_2012/household/data/031_mod_o1_female.dta")
o2_f_2011 = read_dta("Data/Raw Data/bihs_2011_2012/household/data/032_mod_o2_female.dta")
p1_m_2011 = read_dta("Data/Raw Data/bihs_2011_2012/household/data/033_mod_p1_male.dta")
p2_m_2011 = read_dta("Data/Raw Data/bihs_2011_2012/household/data/034_mod_p2_male.dta")
u_m_2011 = read_dta("Data/Raw Data/bihs_2011_2012/household/data/040_mod_u_male.dta")
w1_f_2011 = read_dta("Data/Raw Data/bihs_2011_2012/household/data/045_mod_w1_female.dta")
w2_f_2011 = read_dta("Data/Raw Data/bihs_2011_2012/household/data/046_mod_w2_female.dta")
w3_f_2011 = read_dta("Data/Raw Data/bihs_2011_2012/household/data/047_mod_w3_female.dta")
w4_f_2011 = read_dta("Data/Raw Data/bihs_2011_2012/household/data/048_mod_w4_female.dta")
x1_f_2011 = read_dta("Data/Raw Data/bihs_2011_2012/household/data/049_mod_x1_female.dta")
x2_f_2011 = read_dta("Data/Raw Data/bihs_2011_2012/household/data/050_mod_x2_female.dta")
x3_f_2011 = read_dta("Data/Raw Data/bihs_2011_2012/household/data/051_mod_x3_female.dta")
z1_f_2011 = read_dta("Data/Raw Data/bihs_2011_2012/household/data/060_mod_z1_female.dta")
z2_f_2011 = read_dta("Data/Raw Data/bihs_2011_2012/household/data/061_mod_z2_female.dta")
z3_f_2011 = read_dta("Data/Raw Data/bihs_2011_2012/household/data/062_mod_z3_female.dta")
z4_f_2011 = read_dta("Data/Raw Data/bihs_2011_2012/household/data/063_mod_z4_female.dta")
z5_f_2011 = read_dta("Data/Raw Data/bihs_2011_2012/household/data/064_mod_z5_female.dta")
#
# a_m_2015 = read_dta("Data/Raw Data/bihs_2015/household/data/001_r2_mod_a_male.dta")
# a_f_2015 = read_dta("Data/Raw Data/bihs_2015/household/data/002_r2_mod_a_female.dta")
# b1_m_2015 = read_dta("Data/Raw Data/bihs_2015/household/data/003_r2_male_mod_b1.dta")
# b2_m_2015 = read_dta("Data/Raw Data/bihs_2015/household/data/004_r2_mod_b2_male.dta")
# b3_m_2015 = read_dta("Data/Raw Data/bihs_2015/household/data/005_r2_mod_b3_male.dta")
# b3_f_2015 = read_dta("Data/Raw Data/bihs_2015/household/data/006_r2_mod_b3_female.dta")
# b4_m_2015 = read_dta("Data/Raw Data/bihs_2015/household/data/007_r2_mod_b4_male.dta")
# c_m_2015 = read_dta("Data/Raw Data/bihs_2015/household/data/008_r2_mod_c_male.dta")
# c1_m_2015 = read_dta("Data/Raw Data/bihs_2015/household/data/009_r2_mod_c1_male.dta")
# o1_f_2015 = read_dta("Data/Raw Data/bihs_2015/household/data/042_r2_mod_o1_female.dta")
# o2_f_2015 = read_dta("Data/Raw Data/bihs_2015/household/data/043_r2_mod_o2_female.dta")
# o3_f_2015 = read_dta("Data/Raw Data/bihs_2015/household/data/044_r2_mod_o3_female.dta")
# p1_m_2015 = read_dta("Data/Raw Data/bihs_2015/household/data/045_r2_mod_p1_male.dta")
# p2_m_2015 = read_dta("Data/Raw Data/bihs_2015/household/data/046_r2_mod_p2_male.dta")
# u_m_2015 = read_dta("Data/Raw Data/bihs_2015/household/data/052_r2_mod_u_male.dta")
# w1_f_2015 = read_dta("Data/Raw Data/bihs_2015/household/data/059_r2_mod_w1_female.dta")
# w2_f_2015 = read_dta("Data/Raw Data/bihs_2015/household/data/060_r2_mod_w2_female.dta")
# w3_f_2015 = read_dta("Data/Raw Data/bihs_2015/household/data/061_r2_mod_w3_female.dta")
# w4_f_2015 = read_dta("Data/Raw Data/bihs_2015/household/data/062_r2_mod_w4_female.dta")
# w5_f_2015 = read_dta("Data/Raw Data/bihs_2015/household/data/063_r2_mod_w5_female.dta")
x1_1_f_2015 = read_dta("Data/Raw Data/bihs_2015/household/data/064_r2_mod_x1_1_female.dta")
# x1_2_f_2015 = read_dta("Data/Raw Data/bihs_2015/household/data/065_r2_mod_x1_2_female.dta")
# x2_1_f_2015 = read_dta("Data/Raw Data/bihs_2015/household/data/066_r2_mod_x2_1_female.dta")
# x2_2_f_2015 = read_dta("Data/Raw Data/bihs_2015/household/data/067_r2_mod_x2_2_female.dta")
# x3_f_2015 = read_dta("Data/Raw Data/bihs_2015/household/data/068_r2_mod_x3_female.dta")
# x4_m_2015 = read_dta("Data/Raw Data/bihs_2015/household/data/069_r2_mod_x4_male.dta")
# z1_f_2015 = read_dta("Data/Raw Data/bihs_2015/household/data/078_r2_mod_z1_female.dta")
# z2_f_2015 = read_dta("Data/Raw Data/bihs_2015/household/data/079_r2_mod_z2_female.dta")
# z3_f_2015 = read_dta("Data/Raw Data/bihs_2015/household/data/080_r2_mod_z3_female.dta")
# z4_f_2015 = read_dta("Data/Raw Data/bihs_2015/household/data/081_r2_mod_z4_female.dta")
# z5_f_2015 = read_dta("Data/Raw Data/bihs_2015/household/data/082_r2_mod_z5_female.dta")

###Import nutrition data
(nutrients = 
    read_excel("Data/Raw Data/Nutrient Table/FCDB_7_4_14_LC.xlsx",
        sheet = "UserDB_Main_table"))
  
#drop extra rows of nutrient data
nutrients = nutrients %>%
  filter(Code!="n")%>%
  filter(Code!="SD or min- max")
  
#rename columns
names(nutrients)[3]="foodname_english"
names(nutrients)[4]="foodname_bengali"

#subset the nutrition data to select calorie and edible info
calories = dplyr::select(nutrients, BIHS_code, EDIBLE, ENERGY_kcal) %>%
  filter(!is.na(BIHS_code))

calories$EDIBLE[is.na(calories$EDIBLE)] = "1"
calories$ENERGY_kcal = as.numeric(calories$ENERGY_kcal, na.omit = TRUE) #convert to numeric
calories$EDIBLE = as.numeric(calories$EDIBLE, na.omit = TRUE) #convert to numeric

###import names of menu items from 2015 (assumed to be more comprehensize than 2011)
menucodes = read_excel("Data/Raw Data/bihs_2015/household/documents/000_codebook.xls", 
                       sheet = "064_r2_mod_x1_1_female", range = "C31:D415",col_names = FALSE)

#rename columns
names(menucodes)[1]="menuname"
names(menucodes)[2]="menu"

#count menu items
menu_items = aggregate(a01~menu, data=x1_f_2011, FUN = length) #206 items consumed in 2011
#issue with salt not being separated into iodine/non-iodine in 2011
menu_items = aggregate(a01~x1_05, data=x1_1_f_2015, FUN = length) #180 items consumed in 2015
#1/3 salt is regular, 2/3 iodine (return to this later)


###import names of ingredient items from 2015 (assumed to be more comprehensize than 2011)
ingredientcodes = read_excel("Data/Raw Data/bihs_2015/household/documents/000_codebook.xls", 
                             sheet = "064_r2_mod_x1_1_female", range = "C417:D717", col_names = FALSE)

#rename columns
names(ingredientcodes)[1]="ingredientname"
names(ingredientcodes)[2]="ingredient"

sevenday_items = aggregate(a01~o1_01, data=o1_f_2011, FUN = length) #295 items

```

2. Calculate calories for each recipe
```{r calculate recipe calories}
 
#change the name for menu/cooked weight back to coded variable names
colnames(x1_f_2011)[colnames(x1_f_2011)=="menu"] = "x1_05"
colnames(x1_f_2011)[colnames(x1_f_2011)=="cwgt"] = "x1_09"

#join recipe dataset with menucodes to include menu names
x1_f_2011_m = left_join(x1_f_2011,menucodes,by=c("x1_05"="menu"))


#rejoin the recipe dataset iterating over each ingredient, to add the calorie and edible info for each ingredient
#calculate the specific caloric input of each ingredient = (ingredient weight x calories per 100gram x edible portion)/100

###edit ingredients which have two BIHS codes, but are the same thing
#need to work on the loop, its a struggle
listx = dplyr::select(x1_f_2011_m,contains("x1_07_"))
namesx = names(listx)
namesxx = str_sub(namesx,6,-1)
# 
# recodeingr = function(x){
#   x1_f_2011_m$x = recode(x1_f_2011_m$x,"233=232;90=80;193=181;187=186;258=32;47=46;267=162;188=189")
#  }
# 
# lapply(listx, recode("233=232;90=80;193=181;187=186;258=32;47=46;267=162;188=189"))
# # gsub("")
# 
# for(i in length(namesx)){
#   x1_f_2011_m$[i] = recode(x1_f_2011_m$[i],"233=232;90=80;193=181;187=186;258=32;47=46;267=162;188=189")
# }
# 
# recipes_2011 = x1_f_2011_m%>%
#   dplyr::select(a01,x1_03,x1_05,starts_with("x1_07"),starts_with("x1_08"))%>%
#   unite(3:5,col="ddmmyy",sep="/")
#   reshape2::melt(id.vars=c("a01","x1_03","x1_05"),measure.var=c("names7x", "names8x"))
# 

x1_f_2011_m$x1_07_01 = recode(x1_f_2011_m$x1_07_01,"233=232;90=80;193=181;187=186;258=32;47=46;267=162;188=189") 
x1_f_2011_m$x1_07_02 = recode(x1_f_2011_m$x1_07_02,"233=232;90=80;193=181;187=186;258=32;47=46;267=162;188=189") 
x1_f_2011_m$x1_07_03 = recode(x1_f_2011_m$x1_07_03,"233=232;90=80;193=181;187=186;258=32;47=46;267=162;188=189") 
x1_f_2011_m$x1_07_04 = recode(x1_f_2011_m$x1_07_04,"233=232;90=80;193=181;187=186;258=32;47=46;267=162;188=189") 
x1_f_2011_m$x1_07_05 = recode(x1_f_2011_m$x1_07_05,"233=232;90=80;193=181;187=186;258=32;47=46;267=162;188=189") 
x1_f_2011_m$x1_07_06 = recode(x1_f_2011_m$x1_07_06,"233=232;90=80;193=181;187=186;258=32;47=46;267=162;188=189") 
x1_f_2011_m$x1_07_07 = recode(x1_f_2011_m$x1_07_07,"233=232;90=80;193=181;187=186;258=32;47=46;267=162;188=189") 
x1_f_2011_m$x1_07_08 = recode(x1_f_2011_m$x1_07_08,"233=232;90=80;193=181;187=186;258=32;47=46;267=162;188=189") 
x1_f_2011_m$x1_07_09 = recode(x1_f_2011_m$x1_07_09,"233=232;90=80;193=181;187=186;258=32;47=46;267=162;188=189") 
x1_f_2011_m$x1_07_10 = recode(x1_f_2011_m$x1_07_10,"233=232;90=80;193=181;187=186;258=32;47=46;267=162;188=189")
x1_f_2011_m$x1_07_11 = recode(x1_f_2011_m$x1_07_11,"233=232;90=80;193=181;187=186;258=32;47=46;267=162;188=189") 
x1_f_2011_m$x1_07_12 = recode(x1_f_2011_m$x1_07_12,"233=232;90=80;193=181;187=186;258=32;47=46;267=162;188=189") 
x1_f_2011_m$x1_07_13 = recode(x1_f_2011_m$x1_07_13,"233=232;90=80;193=181;187=186;258=32;47=46;267=162;188=189") 
x1_f_2011_m$x1_07_14 = recode(x1_f_2011_m$x1_07_14,"233=232;90=80;193=181;187=186;258=32;47=46;267=162;188=189") 
#baicha/bacha cabbage/cabbage chital/chital hilsa/jatka mustard/mustard sweetgourd/pumpkin gur/jaggery mirrorcarp/grasscarp

x1_f_2011_I =x1_f_2011_m 
# 
# for(i in 1:length(x1_f_2011_I)) {
#   
#   for(j in seq_along(namesx)) {
#   dplyr::mutate(paste("edible",str_sub(namesx[j],6,-1)) = x1_f_2011_I[,j]) %>%
#   x1_f_2011_I = left_join(x1_f_2011_I,calories,by=c("code"="BIHS_code")) 
#   }
# 
#   dplyr::mutate(paste("kcal",str_sub(namesx[j],6,-1)) = ENERGY_kcal) %>%
#   dplyr::mutate(paste("edible",str_sub(namesx[j],6,-1)) = EDIBLE)
#   dplyr::select(-ENERGY_kcal,-EDIBLE)
# }
# }
# 
#   
# x1_f_2011_I = left_join(x1_f_2011_I,calories,by=c("x1_07_01"="BIHS_code")) %>%
#   dplyr::rename(kcal1=ENERGY_kcal)%>%
#   dplyr::rename(edible1=EDIBLE)%>%
#   mutate(cal1 = x1_08_01*kcal1/100)%>%
#   mutate(ecal1 = x1_08_01*kcal1*edible1/100)
# 


x1_f_2011_I = left_join(x1_f_2011_I,ingredientcodes,by=c("x1_07_01"="ingredient")) %>%
  dplyr::rename(ingredient1=ingredientname)
x1_f_2011_I = left_join(x1_f_2011_I,calories,by=c("x1_07_01"="BIHS_code")) %>%
  dplyr::rename(kcal1=ENERGY_kcal)%>%
  dplyr::rename(edible1=EDIBLE)%>%
  mutate(cal1 = x1_08_01*kcal1/100)%>%
  mutate(ecal1 = x1_08_01*kcal1*edible1/100)


x1_f_2011_I = left_join(x1_f_2011_I,ingredientcodes,by=c("x1_07_02"="ingredient")) %>%
  dplyr::rename(ingredient2=ingredientname)
x1_f_2011_I = left_join(x1_f_2011_I,calories,by=c("x1_07_02"="BIHS_code")) %>%
  dplyr::rename(kcal2=ENERGY_kcal)%>%
  dplyr::rename(edible2=EDIBLE)%>%
  mutate(cal2 = x1_08_02*kcal2/100)%>%
  mutate(ecal2 = x1_08_02*kcal2*edible2/100)
  
x1_f_2011_I = left_join(x1_f_2011_I,ingredientcodes,by=c("x1_07_03"="ingredient")) %>%
  dplyr::rename(ingredient3=ingredientname)
x1_f_2011_I = left_join(x1_f_2011_I,calories,by=c("x1_07_03"="BIHS_code")) %>%
  dplyr::rename(kcal3=ENERGY_kcal)%>%
  dplyr::rename(edible3=EDIBLE)%>%
  mutate(cal3 = x1_08_03*kcal3/100)%>%
  mutate(ecal3 = x1_08_03*kcal3*edible3/100)

x1_f_2011_I = left_join(x1_f_2011_I,ingredientcodes,by=c("x1_07_04"="ingredient")) %>%
  dplyr::rename(ingredient4=ingredientname)
x1_f_2011_I = left_join(x1_f_2011_I,calories,by=c("x1_07_04"="BIHS_code")) %>%
  dplyr::rename(kcal4=ENERGY_kcal)%>%
  dplyr::rename(edible4=EDIBLE)%>%
  mutate(cal4 = x1_08_04*kcal4/100)%>%
  mutate(ecal4 = x1_08_04*kcal4*edible4/100)

x1_f_2011_I = left_join(x1_f_2011_I,ingredientcodes,by=c("x1_07_05"="ingredient")) %>%
  dplyr::rename(ingredient5=ingredientname)
x1_f_2011_I = left_join(x1_f_2011_I,calories,by=c("x1_07_05"="BIHS_code")) %>%
  dplyr::rename(kcal5=ENERGY_kcal)%>%
  dplyr::rename(edible5=EDIBLE)%>%
  mutate(cal5 = x1_08_05*kcal5/100)%>%
 mutate(ecal5 = x1_08_05*kcal5*edible5/100)

x1_f_2011_I = left_join(x1_f_2011_I,ingredientcodes,by=c("x1_07_06"="ingredient")) %>%
  dplyr::rename(ingredient6=ingredientname)
x1_f_2011_I = left_join(x1_f_2011_I,calories,by=c("x1_07_06"="BIHS_code")) %>%
  dplyr::rename(kcal6=ENERGY_kcal)%>%
  dplyr::rename(edible6=EDIBLE)%>%
  mutate(cal6 = x1_08_06*kcal6/100)%>%
 mutate(ecal6 = x1_08_06*kcal6*edible6/100)

x1_f_2011_I = left_join(x1_f_2011_I,ingredientcodes,by=c("x1_07_07"="ingredient")) %>%
  dplyr::rename(ingredient7=ingredientname)
x1_f_2011_I = left_join(x1_f_2011_I,calories,by=c("x1_07_07"="BIHS_code")) %>%
  dplyr::rename(kcal7=ENERGY_kcal)%>%
  dplyr::rename(edible7=EDIBLE)%>%
  mutate(cal7 = x1_08_07*kcal7/100)%>%
 mutate(ecal7 = x1_08_07*kcal7*edible7/100)

x1_f_2011_I = left_join(x1_f_2011_I,ingredientcodes,by=c("x1_07_08"="ingredient")) %>%
  dplyr::rename(ingredient8=ingredientname)
x1_f_2011_I = left_join(x1_f_2011_I,calories,by=c("x1_07_08"="BIHS_code")) %>%
  dplyr::rename(kcal8=ENERGY_kcal)%>%
  dplyr::rename(edible8=EDIBLE)%>%
  mutate(cal8 = x1_08_08*kcal8/100)%>%
 mutate(ecal8 = x1_08_08*kcal8*edible8/100)

x1_f_2011_I = left_join(x1_f_2011_I,ingredientcodes,by=c("x1_07_09"="ingredient")) %>%
  dplyr::rename(ingredient9=ingredientname)
x1_f_2011_I = left_join(x1_f_2011_I,calories,by=c("x1_07_09"="BIHS_code")) %>%
  dplyr::rename(kcal9=ENERGY_kcal)%>%
  dplyr::rename(edible9=EDIBLE)%>%
  mutate(cal9 = x1_08_09*kcal9/100)%>%
 mutate(ecal9 = x1_08_09*kcal9*edible9/100)

x1_f_2011_I = left_join(x1_f_2011_I,ingredientcodes,by=c("x1_07_10"="ingredient")) %>%
  dplyr::rename(ingredient10=ingredientname)
x1_f_2011_I = left_join(x1_f_2011_I,calories,by=c("x1_07_10"="BIHS_code")) %>%
  dplyr::rename(kcal10=ENERGY_kcal)%>%
  dplyr::rename(edible10=EDIBLE)%>%
  mutate(cal10 = x1_08_10*kcal10/100)%>%
 mutate(ecal10 = x1_08_10*kcal10*edible10/100)

x1_f_2011_I = left_join(x1_f_2011_I,ingredientcodes,by=c("x1_07_11"="ingredient")) %>%
  dplyr::rename(ingredient11=ingredientname)
x1_f_2011_I = left_join(x1_f_2011_I,calories,by=c("x1_07_11"="BIHS_code")) %>%
  dplyr::rename(kcal11=ENERGY_kcal)%>%
  dplyr::rename(edible11=EDIBLE)%>%
  mutate(cal11 = x1_08_11*kcal11/100)%>%
 mutate(ecal11 = x1_08_11*kcal11*edible11/100)

x1_f_2011_I = left_join(x1_f_2011_I,ingredientcodes,by=c("x1_07_12"="ingredient")) %>%
  dplyr::rename(ingredient12=ingredientname)
x1_f_2011_I = left_join(x1_f_2011_I,calories,by=c("x1_07_12"="BIHS_code")) %>%
  dplyr::rename(kcal12=ENERGY_kcal)%>%
  dplyr::rename(edible12=EDIBLE)%>%
  mutate(cal12 = x1_08_12*kcal12/100)%>%
 mutate(ecal12 = x1_08_12*kcal12*edible12/100)

x1_f_2011_I = left_join(x1_f_2011_I,ingredientcodes,by=c("x1_07_13"="ingredient")) %>%
  dplyr::rename(ingredient13=ingredientname)
x1_f_2011_I = left_join(x1_f_2011_I,calories,by=c("x1_07_13"="BIHS_code")) %>%
  dplyr::rename(kcal13=ENERGY_kcal)%>%
  dplyr::rename(edible13=EDIBLE)%>%
  mutate(cal13 = x1_08_13*kcal13/100)%>%
 mutate(ecal13 = x1_08_13*kcal13*edible13/100)

x1_f_2011_I = left_join(x1_f_2011_I,ingredientcodes,by=c("x1_07_14"="ingredient")) %>%
  dplyr::rename(ingredient14=ingredientname)
x1_f_2011_I = left_join(x1_f_2011_I,calories,by=c("x1_07_14"="BIHS_code")) %>%
  dplyr::rename(kcal14=ENERGY_kcal)%>%
  dplyr::rename(edible14=EDIBLE)%>%
  mutate(cal14 = x1_08_14*kcal14/100)%>%
 mutate(ecal14 = x1_08_14*kcal14*edible14/100)

#investigate missing items
missing_ing1 = x1_f_2011_I[is.na(x1_f_2011_I$cal1),]
missing_ing = aggregate(a01~x1_07_01, data=missing_ing1, FUN = length)
missing_ing = left_join(missing_ing,menucodes,by=c("x1_07_01"="menu")) %>%
  arrange(desc(a01))
rm(missing_ing1)


#calculate recipe calories
#x1_f_2011_I %>% 
 # mutate(mealcal = rowSums(dplyr::select(x1_f_2011_I,starts_with("cal"))))

calpermeal = dplyr::select(x1_f_2011_I,1:9,12,starts_with("cal"))%>%
  mutate(mealcal=rowSums(.[11:14],na.rm=TRUE),mealcalpergram=mealcal/x1_09)

ecalpermeal = dplyr::select(x1_f_2011_I,1:9,12,starts_with("ecal"))%>%
  mutate(mealecal=rowSums(.[11:14],na.rm=TRUE),mealecalpergram=mealecal/x1_09)                        
```

3. Calculate calories consumed by each individual
```{r calculate individual caloriesE}
#integrate with individual consumption data set and create individual calorie consumption

# #flag for individuals without consumption data
# datacheck = x2_f_2011  %>%
#   group_by(a01,x2_01) %>%
#   summarise(mealdata = n())%>%
#   filter(x2_01<100)%>%
#   dplyr::rename(mid=x2_01)


x2_f_2011_I = left_join(x2_f_2011,calpermeal,by=c("a01","x2_meal"="x1_03","x2_08"="x1_05"))%>%
  dplyr::select(-starts_with("cal"),-starts_with("x1_"))%>%
  mutate(I_mealcal=mealcalpergram*x2_09)

x2_f_2011_I = left_join(x2_f_2011_I,ecalpermeal,by=c("a01","x2_meal"="x1_03","x2_08"="x1_05"))%>%
  dplyr::select(-starts_with("ecal"))%>%
  mutate(I_mealecal=mealecalpergram*x2_09)

daycal_2011_I = x2_f_2011_I %>%
  group_by(a01, x2_01) %>%
  filter(x2_03==1)%>% #filter out if meal not taken
  summarise(I_daycal=sum(I_mealcal,na.rm=TRUE),I_dayecal=sum(I_mealecal,na.rm=TRUE),mealdata=n())%>%
  filter(x2_01<100)%>% #filter out guests
  dplyr::rename(mid=x2_01)


```

4. Calculate BMI
```{r BMI calculation, include=FALSE}
w1_f_2011$BMI = w1_f_2011$w1_03/((w1_f_2011$w1_04/100)^2)
dplyr::na_if(w1_f_2011$BMI,0) #convert zero to NA

```

5. Create Individual Roster
```{r roster_I,results='hide'}

###CREATE INDIVIDUAL ROSTER###
#add BMI and calorie consumption to individual roster_2011
roster_2011_I=left_join(b1_m_2011,w1_f_2011,by=c("a01","mid","sample_type")) %>%
  dplyr::rename(hhid=a01,pregnant=w1_01,lactating=w1_02,
                      weight=w1_03,height=w1_04,gender=b1_01,age=b1_02,
                      relation=b1_03,marital=b1_04,abroad=b1_05,literacy=b1_07,
                    education=b1_08,occupation=b1_10,sampletype=sample_type) %>%
  mutate(agegrp_DST=if_else(age>=60,"60 and up",if_else(age>=40 & age<=59,"40-59",if_else(age>=20 & age<=39,"20-39",as.character(NA)))),
         agegrp_PONE=if_else(age>=45,"45 and up",if_else(age>=20 & age<=44,"20-44",if_else(age>=11 & age<=19,"11-19",
                                                      if_else(age>=6 & age<=10,"6-10",if_else(age>=0 & age<=5,"0-5",as.character(NA)))))))
                                                   
                        
nrow(filter(roster_2011_I,is.na(BMI))) #4507 are missing BMI
occupation_type = aggregate(hhid~occupation, data=roster_2011_I, FUN = length) 


#add individual calorie information
roster_2011_I=left_join(roster_2011_I,daycal_2011_I,by=c("hhid"="a01","mid")) 

roster_2011_I$mealdata[is.na(roster_2011_I$mealdata)] <- 0
 


# count number of household members
roster_2011_I = roster_2011_I %>%
  group_by(hhid) %>%
  mutate(hhsize=n(),
         boy=if_else(age<18 & gender==1,1,0),
         girl=if_else(age<18 & gender==2,1,0),
         man=if_else(age>=18 & gender==1,1,0),
         woman=if_else(age>=18 & gender==2,1,0),
         adult=if_else(boy==0 & girl==0,1,0),
         child=if_else(man==0 & woman==0,1,0),
         otheradult=ifelse(relation>2 & adult==1,1,0),
         porl=if_else(pregnant==1 | lactating==1,1,0),
         spouseabroad=if_else(abroad==1 & relation==2,1,0))



#flag polygamous households
roster_2011_I = roster_2011_I %>%
  group_by(hhid,relation)%>%
  mutate(poly=if_else(n()>1 & relation==2,1,0)) %>%
  ungroup()
nrow(filter(roster_2011_I,poly==1))
#30 individuals are duplicate partners (ie: 15 hh have two spouses)

```

6. Create Household Roster
```{r roster_HH, echo=FALSE}

###create household level roster_2011
roster_2011_hh = roster_2011_I %>%
  group_by(hhid) %>%
  summarise(hhsize = n(), adult=sum(adult),child=sum(child), poly=max(poly),
            boy=sum(boy),girl=sum(girl),otheradult=sum(otheradult),
            porl_hh=sum(porl,na.rm=TRUE), spouseabroad_hh=sum(spouseabroad,na.rm=TRUE),
            mealdata_hhmin=min(mealdata),hhcalperday=sum(I_daycal),hhecalperday=sum(I_dayecal),
            sampletype=first(sampletype))
#all individuals in all households report at least one meal consumed
#6503 households


#calculate AE for the household (alternate options?) 
roster_2011_hh$AE = 1+0.7*(roster_2011_hh$adult-1)+0.5*roster_2011_hh$child

#calculate daily calories per adult equivalent
roster_2011_hh$hhdaycalperAE = roster_2011_hh$hhcalperday/roster_2011_hh$AE
roster_2011_hh$hhdayecalperAE = roster_2011_hh$hhecalperday/roster_2011_hh$AE

#filter individual roster_2011 to create head and spouse roster_2011s
roster_2011_head = filter(roster_2011_I,relation==1) %>%
   mutate(agehead=age, genderhead=gender, 
          maritalhead=marital,
          abroadhead=if_else(abroad==1,1,0),
          lithead=if_else(literacy==4,1,0),
          noschoolhead=if_else(education==99,1,0),
          secondschoolhead=if_else(education==10,1,0),
          agworkhead=if_else(occupation %in% c(1,64:71),1,0),
          BMIhead=BMI,I_daycalhead=I_daycal,I_dayecalhead=I_dayecal) %>%
  dplyr::select(hhid,contains("head"))
#6503 heads          
          
roster_2011_spouse = filter(roster_2011_I,relation==2) %>%
            mutate(agespouse=age,genderspouse=gender,
                   abroadspouse=if_else(abroad==1,1,0),
                   litspouse=if_else(literacy==4,1,0),
                   noschoolspouse=if_else(education==99,1,0),
                   secondschoolspouse=if_else(education==10,1,0),
                   agworkspouse=if_else(occupation %in% c(1,64:71),1,0),
                   BMIspouse=BMI,I_daycalspouse=I_daycal,I_dayecalspouse=I_dayecal)%>%
  dplyr::select(hhid,ends_with("spouse"))
#5225 spouses

#add head and spouse characteristics back to household level roster_2011                   
roster_2011_hh=full_join(roster_2011_hh,roster_2011_head,by="hhid") 
roster_2011_hh=full_join(roster_2011_hh,roster_2011_spouse,by="hhid")
#6518 households = 6503+15 additional spouses in poly hh

#rm(roster_2011_head,roster_2011_spouse) 


dupe_hh = roster_2011_hh %>%
  filter(sampletype==2 |sampletype==3)%>% 
  group_by(hhid) %>% 
  filter(n() > 1)#30 poly HH

roster_2011_hh= distinct(roster_2011_hh,hhid, .keep_all= TRUE) #keeps only one line for each poly HH because HH level var are equivalent

```

7. Calculate village level prices and HH expenditures
```{r expenditures, echo=FALSE,include=FALSE,results='hide'}

villages = aggregate(a01~vcode_n, data=a_m_2011, FUN = length) #318 villages
upazilla = aggregate(a01~uzcode, data=a_m_2011, FUN = length) #279 upazilla


#calculate household level weekly food expenditure
o1_f_2011_hh = left_join(o1_f_2011,a_m_2011,by="a01")%>%
  dplyr::select(a01,contains("o1"),vcode_n)

#calculate village level prices: unit mean and unit median prices if there are more than 3 observations in the village for the food item
prices_village = o1_f_2011_hh%>%
  dplyr::select(vcode_n,o1_01,o1_06,o1_07,o1_08)%>%
  arrange(vcode_n,o1_01,o1_07)%>%
  group_by(o1_01,vcode_n) %>%
  filter(!is.na(o1_07))%>%
  summarise(unitprice=ifelse(n()>3,mean(o1_07),0),medprice=ifelse(n()>3,median(o1_08/o1_06),0))%>%
  dplyr::na_if(0) #convert zero to NA

#join food expenditures with village food prices
o1_f_2011_hh = left_join(o1_f_2011_hh,prices_village,by=c("o1_01","vcode_n"))%>%
  mutate(foodprod=medprice*o1_10,foodother=medprice*o1_11) 

foodexp_hh = o1_f_2011_hh%>%
  group_by(a01) %>%
  summarise(foodpurch_hhwk=sum(o1_08,na.rm=TRUE),foodprod_hhwk=sum(foodprod,na.rm=TRUE),
            foodother_hhwk=sum(foodother,na.rm=TRUE))


#calculate household level weekly nonfood expenditure from monthly
nonfoodexp_m_hh = p1_m_2011 %>%
  group_by(a01) %>%
  summarise(p1_02=sum(p1_02,na.rm=TRUE)) %>%
  mutate(nonfoodexp1_hhwk=p1_02*12/52) %>%
  dplyr::rename(nonfoodexp1_hhmo=p1_02)

#calculate household level weekly nonfood expenditure from annual
nonfoodexp_y_hh = p2_m_2011 %>%
  group_by(a01) %>%
  summarise(p2_03=sum(p2_03,na.rm=TRUE)) %>%
  mutate(nonfoodexp2_hhwk=p2_03/52) %>%
  dplyr::rename(nonfoodexp2_hhyr=p2_03)     

#combine all nonfood exp expenditures
nonfoodexp_hh=left_join(nonfoodexp_m_hh,nonfoodexp_y_hh,by="a01") %>%
  mutate(nonfoodexp_hhwk=nonfoodexp1_hhwk + nonfoodexp2_hhwk) %>%
  dplyr::select(a01,nonfoodexp_hhwk)

#rm(nonfoodexp_m_hh,nonfoodexp_y_hh)

#add food expenditures to household roster_2011
#add expenditures to household roster_2011
#add expenditures to household roster_2011
roster_2011_hh=left_join(roster_2011_hh,nonfoodexp_hh,by=c("hhid"="a01")) %>%
  mutate(nonfoodexp_hhwkpc = nonfoodexp_hhwk/AE)
roster_2011_hh=left_join(roster_2011_hh,foodexp_hh,by=c("hhid"="a01")) %>%
  mutate(foodpurch_hhwkpc = foodpurch_hhwk/AE,
         foodprod_hhwkpc = foodprod_hhwk/AE,
         foodother_hhwkpc = foodother_hhwk/AE)

roster_2011_hh = roster_2011_hh %>%
  mutate(foodshare=if_else(nonfoodexp_hhwk>0,foodpurch_hhwk/(foodpurch_hhwk+nonfoodexp_hhwk),0))

dplyr::na_if(roster_2011_hh$foodshare,0) #convert zero to NA



```

(sidebar) Assistance Type
```{r assistance, echo=FALSE}
#breakdown of assistance type (for all households)
assistance = u_m_2011 %>%
  filter(u01==1) 

assistance_count = aggregate(a01~slno, data=assistance, FUN = length)

# %>%
#   group_by(a01)%>%
#   summarise(u01_hh=n(mid_1)+n(mid_2))
```

8. Summary Tables
```{r summary, echo=FALSE}

### SUMMARY of all 6518 households (ie: 15 hh are mentioned twice because have two spouses)
roster_2011_hh.summary = roster_2011_hh %>%
    psych::describe() %>%
  as_tibble(rownames="rowname") %>%
  dplyr::select(rowname,n,mean,sd)

#print(roster_2011_hh.summary,digits=3)


sample_type = aggregate(mid~sampletype, data=roster_2011_I, FUN = length) #23135 individuals are sample type 2 and 3

sample_type = aggregate(hhid~sampletype, data=roster_2011_hh, FUN = length) #5503 households are sample type 2 and 3


### SUMMARY TABLES FOR D&T SUBSET
# "we restrict the sample to households with male, married heads whose spouses are present and to
# households without pregnant or lactating women. This sample of 3,060 house-holds..." (page 631)

# spouseabroad = roster_2011_hh %>%
#   dplyr::select(hhid,contains("abroad"))
#SIDEBAR: use spouseabroad_hh because its an HH aggregate, not a spouse level var


##DST TABLE 1
roster_hh_DST = roster_2011_hh %>%
  filter(genderhead==1 & maritalhead==2 & abroadhead==0 & poly==0 & porl_hh==0 & spouseabroad_hh==0) 

# breakdown of sample type after filtering on hh characteristics
sample_type = aggregate(hhid~sampletype, data=roster_hh_DST, FUN = length)
#1:FTF Original 634
#2:FTF Additional 610
#3:National Representative 2449

roster_hh_DST = roster_hh_DST  %>%
  filter(sampletype==2 |sampletype==3)
#yields 3059 households

HH_DST = roster_hh_DST %>%
  mutate(DST=1) %>%
  dplyr::select(hhid, DST)

#nrow(filter(roster_hh_DST,is.na(BMIhead))) #86 missing
#nrow(filter(roster_hh_DST,is.na(BMIspouse))) #45 missing


roster_hh_DST.summary = roster_hh_DST %>%
  psych::describe() %>%
  as_tibble(rownames="rowname") %>%
  dplyr::select(rowname,n,mean,sd)

#print(roster_hh_DST.summary,digits=3)


table1= dplyr::bind_cols(roster_2011_hh.summary,roster_hh_DST.summary) %>%
  dplyr::select(-rowname1)%>%
  dplyr::rename(obs_full=n,mean_full=mean,sd_full=sd,obs_sample=n1,mean_sample=mean1,sd_sample=sd1) %>%
  dplyr::filter(rowname=="hhdaycalperAE" |rowname=="hhdayecalperAE" | rowname=="nonfoodexp_hhwkpc" | rowname=="foodpurch_hhwkpc" | rowname=="foodshare" | rowname=="hhsize" | rowname=="AE" | rowname=="boy" | rowname=="girl" | rowname=="otheradult"
                | rowname=="agehead" |rowname=="lithead" |rowname=="noschoolhead" |rowname=="secondschoolhead" |rowname=="agworkhead" |rowname=="BMIhead"
                | rowname=="agespouse" |rowname=="litspouse" |rowname=="noschoolspouse" |rowname=="secondschoolspouse" |rowname=="agworkspouse" |rowname=="BMIspouse") 

#%>%
 # dplyr::arrange(desc(obs_full))

#x

kable(table1,booktabs=TRUE,digits=2,caption="Table 1", col.names=c("Variable","N","Mean","SD","N","Mean","SD"),align='r')%>%
  kable_styling(full_width=TRUE)%>%
  pack_rows("Household Head",8,13)%>%
  pack_rows("Spouse",14,19)%>%
  pack_rows("Expenditures",20,22)%>%
  add_header_above(c(" "=1,"All Households"=3,"D&T Sample"=3))



###TABLE 3
roster_I_DST=left_join(roster_2011_I,HH_DST,by="hhid")%>%
  mutate(BMIunder=if_else(BMI<18.5,(18.5-BMI)/18.5,0),
         adultgrp=if_else(relation==1,"head",if_else(relation==2,"spouse",if_else(otheradult==1,"otheradult",as.character(NA)))))%>%
   filter(!is.na(agegrp_DST),!is.na(BMI),!is.na(adultgrp),!is.na(DST))%>%
  dplyr::select(hhid,mid,DST,agegrp_DST,adultgrp,BMI,BMIunder)

#%>%
 # reshape2::cast(agegrp~adultgrp,fun.aggregate=c(mean,sd,n))

#roster_I_DST$DST[is.na(roster_I_DST$DST)]<-0 #convert zero to NA
 

table3= roster_I_DST %>%
  group_by(agegrp,adultgrp) %>%
  summarise(mean=mean(BMIunder),se=sd(BMIunder)/sqrt(length(BMIunder)),n=n())%>%
  reshape2::melt(id.vars=c("agegrp","adultgrp"),measure.var=c("mean","se","n"))%>%
  dplyr::arrange(agegrp)%>%
  unite(agegrp_DST,variable,col="agegrp_var",sep="_")%>%
  dcast(agegrp_DST_var~adultgrp,value.var = "value")%>%
  separate(agegrp_DST_var,into=c("agegrp","var"),"_")%>%
  dplyr::select(var,head,spouse,otheradult)


kable(table3,booktabs=TRUE,digits=3,caption="Table 3: BMI Shortfalls", col.names=c("","Heads","Spouses","Other Adults"),align='r')%>%
  kable_styling(full_width=TRUE)%>%
  pack_rows("Ages 20-39",1,3)%>%
  pack_rows("Ages 40-59",4,6)%>%
  pack_rows("Ages 60 and up",7,9)

#%>%
 # add_header_above(c(" "=1,"All Households"=3,"D&T Sample"=3))



#PONE sample
roster_hh_PONE = roster_2011_hh %>%
   filter(sampletype==2 |sampletype==3) 

roster_I_PONE = roster_2011_I %>%
   filter(sampletype==2 |sampletype==3) %>%
  filter(!is.na(mealdata)) #22173 individuals with 24hr consumption data

roster_I_PONE.summary = roster_I_PONE %>%
    psych::describe() %>%
  as_tibble(rownames="rowname") %>%
  dplyr::select(rowname,n,mean,sd)

roster_hh_PONE.summary = roster_hh_PONE %>%
    psych::describe() %>%
  as_tibble(rownames="rowname") %>%
  dplyr::select(rowname,n,mean,sd)

```


```{r references}

```

