---
title: "Coding_Variables_03_11"
author: "Li Ju"
date: "3/11/2021"
output: html_document
---

Set working directory and install packages
```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE,root.dir='/Users/juli/Desktop/BIHS/master/BIHS_Project ',warning = FALSE, message=FALSE)
options(scipen=999)
set.seed(12345)
###  Check for and load Packages   ###
#library(installr)
#updateR()
# ## get packages installed
# packs = as.data.frame(installed.packages(.libPaths()[1]), stringsAsFactors = F)
# 
# ## and now re-install install packages using install.packages()
# install.packages(packs$Package)

## Clear worksace
rm(list = ls())
gc()

#writeLines('PATH="${RTOOLS40_HOME}\\usr\\bin;${PATH}"', con = "~/.Renviron")

## This function will check if a package is installed, and if not, install it
pkgTest  =  function(x) {
  if (!require(x, character.only = TRUE))
  {
    install.packages(x, dep = TRUE)
    if(!require(x, character.only = TRUE)) stop("Package not found")
  }
}

## These lines load the required packages
packages  =  c('data.table','tidyverse','haven','stargazer','plm','lubridate','survey','psych','knitr','xtable','tables','kableExtra','fuzzyjoin','MASS','matrixcalc','car','stringr','styler','readxl','magrittr','sjmisc','readxl','srvyr','gdata','labelled')

#,) ## you can add more packages here
lapply(packages, pkgTest)




```



1. Import BIHS data

```{r}
# Read in data for project

setwd("/Users/juli/Desktop/BIHS/master/BIHS_Project/Data")

#this pulls in all 2015 household level files except the WEAI
filenames<-grep(list.files(path="./Raw Data/bihs_2015/household/data"),pattern=c("weai","h"),inv=TRUE,value=TRUE)
names<-gsub(".dta","",filenames)

 for(i in names){
   filepath <- file.path(paste("./Raw Data/bihs_2015/household/data/",i,".dta",sep=""))
   if (i == "003_r2_male_mod_b1") {
     assign(paste("b1_male_2015"),haven::read_dta(filepath))
   }
   assign(paste(substring(i,12),"_2015",sep=""),haven::read_dta(filepath))
 }

#task(completed): inputagain "_mod_b1_2015" and rename to "b1_male_2015"


#read in the 2015 census and 2015 consumption file for now
#census_2015 = read_dta("./Raw Data/bihs_2015_2012/census/data/001_census_ftf.dta")

#x1_1_f_2015 = read_dta("./Raw Data/bihs_2015/household/data/064_r2_mod_x1_1_female.dta")




#import names of menu items from the 2015 codebook
#this is assumed to be more comprehensize than 2015 and also available in excel
menucodes = read_excel("./Raw Data/bihs_2015/household/documents/000_codebook.xls", 
                       sheet = "064_r2_mod_x1_1_female", range = "C31:D415",col_names = c("menuname","menu"))

# task - aggregate `x1_1` `x1_2`

#count menu items

# task - rename x1_05 -> menu select the first 41 columns(drop the last one)
# rename x1_2 table x1_05 ->menu
x1_1_female_2015 = x1_1_female_2015 %>% 
                  rename(menu = x1_05) %>% 
                  select(1:41)
x1_2_female_2015 = x1_2_female_2015 %>% rename(menu = x1_05)
# task - aggregate `x1_1` `x1_2` to `x1_female_2015`
x1_female_2015 = rbind(x1_1_female_2015, x1_2_female_2015)

menu_items = aggregate(a01~menu, data=x1_female_2015, FUN = length)%>%
  left_join(menucodes,by=c("menu"))%>%
dplyr::rename("menucode"="menu","hh_num" = "a01")%>%
  arrange(desc(hh_num))
#206 items consumed in 2015
#issue with salt not being separated into iodine/non-iodine in 2015
#menu_items = aggregate(a01~x1_05, data=x1_1_f_2015, FUN = length) #180 items consumed in 2015
#1/3 salt is regular, 2/3 iodine (return to this later)


###import names of ingredient items from 2015 (assumed to be more comprehensize than 2015)
ingredientcodes = read_excel("./Raw Data/bihs_2015/household/documents/000_codebook.xls", 
                             sheet = "064_r2_mod_x1_1_female", range = "C417:D717", col_names =c("ingredientname","ingredient"))%>%
 add_row(ingredientname="Salt",ingredient=252)

occupationcodes=read_excel("./Raw Data/bihs_2015/household/documents/000_codebook.xls", 
                             sheet ="003_r2_male_mod_b1", range = "C106:D182", col_names = c("occupation_name","occupation_code"))




rm(filenames,filepath,i,names,x1_1_f_2015)

```


Coding for table `v1`:

```{r}
#select all the household having any members who are migrants
library(tidyverse)
v1_male_2015 = v1_male_2015%>%filter(v1_01 == 1)%>%
  select(-c(v1_01, Flag_v1))%>%
```

```{r}
v1_male_2015[v1_male_2015$v1_14 == 2, ]$v1_14 = 0
```

```{r}
#the proportion of sending home remittance group by education level
v1_male_2015%>%group_by(v1_07)%>%
  summarise(mean(v1_14))
```
```{r}
#explore correlation between `how was the migrant expenses paid` and `sending home remittance`
corr_13_prop_14 = v1_male_2015%>%group_by(v1_13)%>%
  summarise(mean(v1_14))
plot(corr_13_prop_14)
```

Coding for table `v2`:

```{r}
v2_male_2015 = v2_male_2015%>%filter(v2_01 == 1)
```

```{r}
v2_male_2015_pivot = v2_male_2015%>%
  mutate(average_remittance = v2_06/v2_05)%>%
  pivot_longer(cols = v2_08a:v2_08c, names_to = "v2_08",values_drop_na = TRUE)%>%
  dplyr::select(-v2_08)%>%
  dplyr::rename(v2_08=value)
```

```{r}
#figure out the money mostly been cut off - interesting!
#3:health
#4:consumption(food, cloth) 
v2_male_2015_pivot%>%group_by(v2_08)%>%
  summarise(n = n())
```
```{r}
mean(v2_male_2015_pivot[v2_male_2015_pivot$v2_08 == 3 | v2_male_2015_pivot$v2_08 == 4, ]$v2_06)
mean(v2_male_2015_pivot$v2_06)
```

Coding for table `v3`:

```{r}
v3_male_2015 = v3_male_2015%>%filter(v3_01 == 1)
v2_3_male_2015 = merge(x = v2_male_2015, y = v3_male_2015, by = "a01", all = TRUE)

```

```{r}
v2_3_male_2015_both = v2_3_male_2015%>%filter(v2_01 == 1 & v3_01 == 1)%>%
  mutate(net_remittance = v2_06 - v3_06)
nrow(v2_3_male_2015_both[v2_3_male_2015_both$net_remittance<0,])
nrow(v2_3_male_2015_both[v2_3_male_2015_both$net_remittance==0,])
nrow(v2_3_male_2015_both[v2_3_male_2015_both$net_remittance>0,])
```

Coding for table `v4`:

```{r}
v4_male_2015 = v4_male_2015%>%mutate(sum_other_income = v4_01+v4_02+v4_03+v4_04+v4_05+v4_06+v4_07+v4_08+v4_09+v4_10+v4_11+v4_12)
v2_3_4_male_2015 = merge(x = v2_3_male_2015, y = v4_male_2015, by = "a01", all = TRUE)
```

Coding for table 'I3':

```{r}
i3_male_2015%>%group_by(i3_08)%>%summarise(mean(i3_04),mean(i3_05), mean(i3_06),mean(i3_07))
```

```{r}
i3_male_2015_NGO_help = i3_male_2015%>%filter(i3_08 ==1)
nrow(i3_male_2015_NGO_help)
```

Coding for table `I4`:

```{r}
i4_male_2015 = i4_male_2015%>%mutate(total_expenditure = i4_17+i4_18+i4_19+i4_20)
```

Coding for table `T1`:

```{r}
t1_male_2015 = t1_male_2015%>%filter(t1_02a == 1)
```

Coding for table `T2`:

```{r}
t2_male_2015 = t2_male_2015%>%filter(t2_03 == 1 & !is.na(t2_06))
t2_male_2015%>%group_by(t2_07)%>%
summarise(mean(t2_06))
```


________________________

3. Select variables from BIHS data

```{r}
#select y6a data
selected_y6a = y6a_female_2015%>%
  dplyr::select("a01", "hh_type","y6a_01","y6a_02","y6a_03", "y6a_04_1","y6a_04_2","y6a_04_3")%>%
  pivot_longer(cols = y6a_04_1:y6a_04_3, names_to = "y6a_04",values_drop_na = TRUE)%>%
  dplyr::select(-y6a_04)%>%
  dplyr::rename(y6a_04=value)
selected_y6a$clinic_access = ifelse((selected_y6a$y6a_02 == 999), 0, 1)
```


```{r}
#select y8 data
selected_y8 = y8_female_2015%>%
  dplyr::select("a01", "hh_type","y8_01","y8_03","y8_04",contains("y8_05"),"y8_06",contains("y8_07"))%>%
  pivot_longer(cols = y8_05_1:y8_05_6, names_to = "y8_05",values_drop_na = TRUE)%>%
  dplyr::select(-y8_05)%>%
  dplyr::rename(y8_05=value)%>%
  pivot_longer(cols = y8_07_1:y8_07_6, names_to = "y8_07",values_drop_na = TRUE)%>%
  dplyr::select(-y8_07)%>%
  dplyr::rename(y8_07=value)
```

```{r}
#select I1 data
#question: what should we do to the NA values? (on quantity, reasons, etc.)
selected_i1 = i1_male_2015
```

```{r}
#select I2 data
selected_i2 = i2_male_2015
selected_i2$i2_02_1 = ifelse((selected_i2$i2_02_1 == 99999), 0, selected_i2$i2_02_1)
var_label(selected_i2$i2_02_1) <- "End of Month food grain stock paddy, December 2013 (kg)"
```

```{r}
#select I2A data
selected_i2a = i2a_male_2015
```

```{r}
#select I5 data
selected_i5 = i5_male_2015%>%
  mutate_at(.vars = c("i5_07","i5_08","i5_09","i5_10", "i5_11", "i5_12","i5_13","i5_14","i5_15","i5_16"), funs(ifelse(. == 1, 1, 0)))

```

```{r}
#select R01/R03 data
selected_r01r03 = r_male_2015%>%
  dplyr::select("a01", "hh_type", contains("r01"), "r03")

#pivot_longer mid columns w/out deleting the row where mid is NA

#code "2" and "NA" to 0
selected_r01r03$r01g = ifelse((selected_r01r03$r01g == 1), 1, 0)
selected_r01r03$r01g[is.na(selected_r01r03$r01g)] <- 0

#code the 1st mid column to "0" if the previous column said "0" (not applicable)
selected_r01r03$r01h = ifelse((selected_r01r03$r01g == 1), selected_r01r03$r01h,0)
selected_r01r03$r01h[is.na(selected_r01r03$r01h)] <- 0

#same procedure on r01n and r01o
selected_r01r03$r01n = ifelse((selected_r01r03$r01n == 1), 1, 0)
selected_r01r03$r01n[is.na(selected_r01r03$r01n)] <- 0

selected_r01r03$r01o = ifelse((selected_r01r03$r01n == 1), selected_r01r03$r01o,0)
selected_r01r03$r01o[is.na(selected_r01r03$r01o)] <- 0

#pivot longer mid columns
selected_r01r03 = selected_r01r03%>%
  pivot_longer(cols = r01h:r01h_3, names_to = "r01h",values_drop_na = TRUE)%>%
  dplyr::select(-r01h)%>%
  dplyr::rename(r01h=value)%>%
  pivot_longer(cols = r01o:r01o_3, names_to = "r01o",values_drop_na = TRUE)%>%
  dplyr::select(-r01o)%>%
  dplyr::rename(r01o=value)

#reorder columns
selected_r01r03 <- selected_r01r03[c("a01","hh_type","r01","r01a","r01b","r01c","r01d","r01e","r01f","r01g","r01h","r01i","r01j","r01k","r01l","r01m","r01n","r01o","r03")]

#set value label to the new column
var_label(selected_r01r03$r01g) <- "Is there any member/members in the hh who very rarely or does/do not use the lat"
var_label(selected_r01r03$r01h) <- "If yes, who are they?(mid)"
var_label(selected_r01r03$r01n) <- "Is there any cleansing agent at the hand wash area?"
var_label(selected_r01r03$r01o) <- "If yes, then list all the items that are there in the hand wash area."

```

```{r}
#select U data
selected_u = u_male_2015%>%
  dplyr::select("a01", "hh_type","slno","u01","mid_1","mid_2","u02","u03","u04","u05","u06","u07","u09","u10","u08")%>%
  pivot_longer(cols = mid_1:mid_2, names_to = "mid",values_drop_na = TRUE)%>%
  dplyr::select(-mid)%>%
  dplyr::rename(mid=value)

#set value label to the new column
var_label(selected_u$mid) <- "Member ID"

```


